name: Build Custom Equicord

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup PNPM
        uses: pnpm/setup@v2.1.0
        with:
          runtime: node@v24
          require-lockfile: true

      - name: Build desktop
        run: pnpm buildStandalone

      - name: Build web
        run: pnpm buildWebStandalone

      - name: Upload builds
        uses: actions/upload-artifact@v4
        with:
          name: Equicord2-build
          path: dist/
          if-no-files-found: error
